@HOST = http://localhost:8888
@C_TYPE = application/json
@H-Access-Token = a
@H-Mananger-Token = b

### TEST
GET {{HOST}}/

###
GET {{HOST}}/service/test

###
GET {{HOST}}/service/r

######## DB test_db.flex_test table
### MYSQL  List
POST {{HOST}}/db/mysql/list
Content-Type:{{C_TYPE}}

{"page":1,"q":""}

### MYSQL insert
POST {{HOST}}/db/mysql/insert
Content-Type:{{C_TYPE}}

{"title" : "테스트"}

### MYSQL edit
POST {{HOST}}/db/mysql/edit
Content-Type:{{C_TYPE}}

{"id" : 5}

### MYSQL update
POST {{HOST}}/db/mysql/update
Content-Type:{{C_TYPE}}

{"id" : 5, "title" : "테스트 업데이트3"}

### MYSQL delete
POST {{HOST}}/db/mysql/delete
Content-Type:{{C_TYPE}}

{"id" : 5}



### POSTGRES  List
POST {{HOST}}/db/pgsql/list
Content-Type:{{C_TYPE}}

{"page":1,"q":""}

### POSTGRES insert
POST {{HOST}}/db/pgsql/insert
Content-Type:{{C_TYPE}}

{"title" : "테스트"}

### POSTGRES edit
POST {{HOST}}/db/pgsql/edit
Content-Type:{{C_TYPE}}

{"id" : 5}

### POSTGRES update
POST {{HOST}}/db/pgsql/update
Content-Type:{{C_TYPE}}

{"id" : 5, "title" : "테스트 업데이트3"}

### POSTGRES delete
POST {{HOST}}/db/pgsql/delete
Content-Type:{{C_TYPE}}

{"id" : 5}

##### Distinct
### mysql 
POST {{HOST}}/db/mysql/distinct
Content-Type:{{C_TYPE}}

### pgsql 
POST {{HOST}}/db/pgsql/distinct
Content-Type:{{C_TYPE}}


##### Join
### mysql 
POST {{HOST}}/db/mysql/join
Content-Type:{{C_TYPE}}

### pgsql 
POST {{HOST}}/db/pgsql/join
Content-Type:{{C_TYPE}}


##### GroupBy
### mysql 
POST {{HOST}}/db/mysql/groupby
Content-Type:{{C_TYPE}}

### pgsql 
POST {{HOST}}/db/pgsql/groupby
Content-Type:{{C_TYPE}}


##### Sub Query
### mysql 
POST {{HOST}}/db/mysql/subquery
Content-Type:{{C_TYPE}}

### pgsql 
POST {{HOST}}/db/pgsql/subquery
Content-Type:{{C_TYPE}}