@HOST = http://localhost:8888
@C_TYPE = application/json
@H-Access-Token = a
@H-Mananger-Token = b

### TEST
GET {{HOST}}/

###
GET {{HOST}}/service/test

###
GET {{HOST}}/service/r

######## DB test_db.flex_test table
### DB List
POST {{HOST}}/db/list
Content-Type:{{C_TYPE}}

{"page":1,"q":""}

### DB insert
POST {{HOST}}/db/insert
Content-Type:{{C_TYPE}}

{"title" : "테스트"}


### DB edit
POST {{HOST}}/db/edit
Content-Type:{{C_TYPE}}

{"id" : 5}

### DB update
POST {{HOST}}/db/update
Content-Type:{{C_TYPE}}

{"id" : 5, "title" : "테스트 업데이트3"}


### DB delete
POST {{HOST}}/db/delete
Content-Type:{{C_TYPE}}

{"id" : 5}